// This file is generated by tonic-build, but we need to declare the module
// The actual generated code will be in the target directory after building

// Include the generated protobuf code
pub mod graphyne {
    tonic::include_proto!("graphyne");
}

// Re-export for convenience
pub use graphyne::*;
